# File: /netlify.toml - Version 1.1
# Netlify configuration for qfology Next.js application
# Simplified configuration to fix deployment issues

[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  GITHUB_PAGES = "false"
  NODE_VERSION = "18"

# Essential Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"