# File: /netlify.toml
# Netlify configuration for qfology Next.js application
# Ensures API routes work properly with Netlify Functions

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  GITHUB_PAGES = "false"
  NODE_VERSION = "18"

# Essential Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

# Critical redirects for Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle all other routes through Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200